# Generated by Django 5.0.14 on 2026-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SumurAirTanahModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('jenis_sumur', models.CharField(blank=True, max_length=50, null=True)),
                ('kedalaman_sumur', models.FloatField(blank=True, null=True)),
                ('jenis_pompa', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_pompa', models.FloatField(blank=True, null=True, verbose_name='Debit Pompa (l/dtk)')),
                ('tahun_pembangunan', models.IntegerField(blank=True, null=True)),
                ('das', models.CharField(blank=True, max_length=100, null=True, verbose_name='DAS')),
                ('ws', models.CharField(blank=True, max_length=100, null=True, verbose_name='WS')),
                ('keterangan', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Sumur Air Tanah',
                'verbose_name_plural': 'Sumur Air Tanah',
                'db_table': 'tb_sumur_air_tanah',
            },
        ),
    ]
