# Generated by Django 5.0.14 on 2026-04-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='tb_user',
        ),
    ]
