# Generated by Django 5.0.14 on 2026-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
