# Generated by Django 5.0.14 on 2026-04-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_jabatanmodel_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jabatanmodel',
            table='user_jabatan',
        ),
    ]
