# Generated by Django 5.0.14 on 2026-04-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_alter_jabatanmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPKModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('kode', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'PPK',
                'verbose_name_plural': 'PPK',
                'db_table': 'tb_ppk',
            },
        ),
        migrations.DeleteModel(
            name='JabatanModel',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('satker', 'Satker'), ('ppk', 'PPK')], max_length=30, null=True, verbose_name='Role'),
        ),
    ]
