# Generated by Django 5.0.14 on 2026-04-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_ppkmodel_delete_jabatanmodel_alter_usermodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('kode', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Satker',
                'verbose_name_plural': 'Satker',
                'db_table': 'tb_satker',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ppk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.ppkmodel'),
        ),
        migrations.AlterField(
            model_name='ppkmodel',
            name='kode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('ppk', 'PPK'), ('staff_ppk', 'Staff PPK'), ('staff_satker', 'Staff Satker')], max_length=30, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.satkermodel'),
        ),
    ]
