# Generated by Django 5.0.14 on 2026-04-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='data_name',
        ),
    ]
