# Generated by Django 5.0.14 on 2026-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_activitylogmodel_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogmodel',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
