# Generated by Django 5.0.14 on 2026-05-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylogmodel_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinsiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provinsi', models.CharField(blank=True, max_length=100)),
                ('singkatan', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': ('Data Provinsi',),
                'verbose_name_plural': 'Provinsi',
                'db_table': 'tb_provinsi',
            },
        ),
        migrations.CreateModel(
            name='KabupatenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kabupaten', models.CharField(blank=True, max_length=100)),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provinsimodel')),
            ],
            options={
                'verbose_name': 'Data Kabupaten',
                'verbose_name_plural': 'Kabupaten',
                'db_table': 'tb_kabupaten',
            },
        ),
    ]
