# Generated by Django 5.0.14 on 2026-04-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.CharField(blank=True, choices=[('Papua Barat', 'Papua Barat'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volume_sabo', models.FloatField(blank=True, null=True, verbose_name='Volume Sabo (m3)')),
                ('panjang', models.FloatField(blank=True, null=True, verbose_name='Panjang (m)')),
                ('tinggi', models.FloatField(blank=True, null=True, verbose_name='Tinggi (m)')),
                ('lebar', models.FloatField(blank=True, null=True, verbose_name='Lebar (m)')),
                ('tahun_mulai', models.IntegerField(blank=True, null=True, verbose_name='Tahun Mulai')),
                ('tahun_selesai', models.IntegerField(blank=True, null=True, verbose_name='Tahun Selesai')),
                ('pengelola', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Keterangan')),
                ('irigasi', models.FloatField(blank=True, null=True, verbose_name='Irigasi (Ha)')),
                ('lain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lain-lain')),
                ('latitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status_aset', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Aset')),
                ('penamaan_bmn', models.CharField(blank=True, max_length=120, null=True, verbose_name='Penamaan BMN')),
            ],
            options={
                'verbose_name': 'Pengendali Sedimen',
                'verbose_name_plural': 'Pengendali Sedimen',
                'db_table': 'tb_checkdam',
            },
        ),
        migrations.CreateModel(
            name='FotoCheckDamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='dokumentasi/checkdam/', verbose_name='foto')),
                ('checkdam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='pengendaliSedimen.checkdammodel')),
            ],
            options={
                'db_table': 'tb_checkdam_dokumentasi',
            },
        ),
    ]
