# Generated by Django 5.0.14 on 2026-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengendaliSedimen', '0003_alter_checkdammodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdammodel',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
