# Generated by Django 5.0.14 on 2026-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbungModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.CharField(blank=True, choices=[('Papua Barat', 'Papua Barat'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipe_konstruksi', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_genangan', models.FloatField(blank=True, null=True)),
                ('volume_tampungan', models.FloatField(blank=True, null=True)),
                ('lebar', models.FloatField(blank=True, null=True)),
                ('panjang', models.FloatField(blank=True, null=True)),
                ('tinggi', models.FloatField(blank=True, null=True)),
                ('irigasi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Irigasi (Ha)')),
                ('ternak', models.IntegerField(blank=True, null=True, verbose_name='Ternak (ekor)')),
                ('air_baku', models.FloatField(blank=True, null=True, verbose_name='Air Baku (ltr/dtk)')),
                ('lainnya', models.CharField(blank=True, max_length=100, null=True)),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Rusak Ringan', 'Rusak Ringan'), ('Rusak Berat', 'Rusak Berat')], max_length=100)),
                ('volume_saat', models.FloatField(blank=True, null=True, verbose_name='Volume Saat Ini (m3)')),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aset Embung',
                'verbose_name_plural': 'Aset Embung',
                'db_table': 'tb_embung',
            },
        ),
    ]
