# Generated by Django 5.0.14 on 2026-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embung', '0002_embungmodel_created_by_embungmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embungmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embungmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
