# Generated by Django 5.0.14 on 2026-05-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embung', '0005_alter_embungmodel_provinsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embungmodel',
            name='provinsi',
        ),
    ]
