# Generated by Django 5.0.14 on 2026-04-29 14:39

import apps.peta_sebaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetaSeabaranModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, verbose_name='Nama File')),
                ('jenis', models.CharField(blank=True, max_length=100, verbose_name='Jenis File')),
                ('file', models.FileField(blank=True, upload_to=apps.peta_sebaran.models.PetaSeabaranModel.path_file, verbose_name='Unggah File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Peta Sebaran Aset',
                'verbose_name_plural': 'Peta Sebaran Aset',
                'db_table': 'tb_peta_sebaran',
            },
        ),
    ]
