# Generated by Django 5.0.14 on 2026-04-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BendungModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.CharField(blank=True, choices=[('Papua Barat', 'Papua Barat'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sungai', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_bendung', models.CharField(blank=True, max_length=100, null=True)),
                ('tinggi', models.FloatField(blank=True, null=True)),
                ('lebar', models.FloatField(blank=True, null=True)),
                ('debit_intake_musim_hujan', models.FloatField(blank=True, null=True)),
                ('debit_intake_musim_kemarau', models.FloatField(blank=True, null=True)),
                ('tahun_mulai', models.IntegerField(blank=True, null=True)),
                ('tahun_rehab', models.IntegerField(blank=True, null=True, verbose_name='Tahun Rehab Terakhir')),
                ('kondisi', models.CharField(blank=True, choices=[('Berfungsi/Baik', 'Berfungsi/Baik'), ('Berfungsi/Rusak', 'Berfungsi/Rusak'), ('Rusak Berat', 'Rusak Berat')], max_length=100, null=True)),
                ('irigasi', models.FloatField(blank=True, null=True)),
                ('lain_lain', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude1', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude1', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status_aset', models.CharField(blank=True, max_length=100, null=True)),
                ('penamaan_bmn', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Bendung',
                'verbose_name_plural': 'Aset Bendung',
                'db_table': 'tb_bendung',
            },
        ),
        migrations.CreateModel(
            name='FotoBendungModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='dokumentasi/bendung/', verbose_name='Foto/Dokumentasi')),
                ('bendung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='bendung.bendungmodel')),
            ],
            options={
                'verbose_name': 'Dokumentasi Bendung',
                'verbose_name_plural': 'Dokumentasi Bendung',
                'db_table': 'tb_bendung_dokumentasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
