# Generated by Django 5.0.14 on 2026-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendung', '0002_bendungmodel_created_by_bendungmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bendungmodel',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
