# Generated by Django 5.0.14 on 2026-04-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TanggulSungaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lokasi_sungai', models.CharField(blank=True, max_length=100, null=True)),
                ('panjang_sungai', models.FloatField(blank=True, null=True)),
                ('nama_sungai', models.CharField(blank=True, max_length=120, null=True)),
                ('das', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('jenis_konstruksi', models.CharField(blank=True, choices=[('Talud Pasang Batu', 'Talud Pasang Batu'), ('Pasang Batu', 'Pasang Batu'), ('Bronjong', 'Bronjong')], max_length=120, null=True)),
                ('panjang_tanggul', models.FloatField(blank=True, null=True)),
                ('tinggi_tanggul', models.FloatField(blank=True, null=True)),
                ('kondisi_sisi_kanan', models.CharField(blank=True, max_length=100, null=True)),
                ('kondisi_sisi_kiri', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_pembuatan', models.IntegerField(blank=True, null=True)),
                ('status_aset', models.CharField(blank=True, max_length=100, null=True)),
                ('penamaan_bmn', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Tanggul Sungai',
                'verbose_name_plural': 'Tanggul Sungai',
                'db_table': 'tb_tanggul_sungai',
            },
        ),
        migrations.CreateModel(
            name='FotoTanggulSungaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='dokumentasi/tanggul/', verbose_name='File Dokumentasi')),
                ('tanggul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='tanggulSungai.tanggulsungaimodel')),
            ],
            options={
                'verbose_name': 'Dokumentasi Tanggul Sungai',
                'verbose_name_plural': 'Dokumentasi Tanggul Sungai',
                'db_table': 'tb_tanggul_sungai_dokumentasi',
            },
        ),
    ]
