# Generated by Django 5.0.14 on 2026-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanggulSungai', '0003_alter_tanggulsungaimodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanggulsungaimodel',
            name='jenis_konstruksi',
            field=models.CharField(blank=True, choices=[('Talud, Pasang Batu', 'Talud, Pasang Batu'), ('Talud, Pasang Batu & Bronjong', 'Talud, Pasang Batu & Bronjong'), ('Pasang Batu', 'Pasang Batu'), ('Bronjong', 'Bronjong')], max_length=120, null=True),
        ),
    ]
