# Generated by Django 5.0.14 on 2026-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengamanPantaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.CharField(blank=True, choices=[('Papua Barat', 'Papua Barat'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True)),
                ('kabupaten', models.CharField(blank=True, choices=[('Kabupaten Manokwari', 'Kabupaten Manokwari'), ('Kabupaten Manokwari Selatan', 'Kabupaten Manokwari Selatan'), ('Kabupaten Maybrat', 'Kabupaten Maybrat'), ('Kabupaten Pegunungan Arfak', 'Kabupaten Pegunungan Arfak'), ('Kabupaten Teluk Bintuni', 'Kabupaten Teluk Bintuni'), ('Kabupaten Teluk Wondama', 'Kabupaten Teluk Wondama'), ('kabupaten Kaimana', 'Kabupaten Kaimana'), ('kabupaten Fakfak', 'Kabupaten Fakfak'), ('Kota Sorong', 'Kota Sorong'), ('Kabupaten Sorong', 'Kabupaten Sorong'), ('kabupaten Raja Ampat', 'Kabupaten Raja Ampat')], max_length=100, null=True, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kewenangan', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_bangunan', models.CharField(choices=[('Revetman', 'Revetman'), ('Break Water', 'Break Water'), ('Seawall', 'Seawall'), ('Pasangan Batu', 'Pasangan Batu'), ('Tanggul Laut', 'Tanggul Laut'), ('Revetman', 'Revetman'), ('Revetman', 'Revetman')], max_length=100)),
                ('panjang', models.FloatField(blank=True, null=True)),
                ('lebar_puncak', models.FloatField(blank=True, null=True)),
                ('kemiringan', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Beton', 'Beton'), ('Pasangan Batu', 'Pasangan Batu')], max_length=100, null=True)),
                ('struktur', models.CharField(blank=True, choices=[('Buis Beton', 'Buis Beton'), ('Kubus Beton', 'Kubus Beton'), ('Talud', 'Talud')], max_length=100, null=True)),
                ('tahun_mulai', models.IntegerField(blank=True, null=True)),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('dibangun_oleh', models.CharField(default='BWS PB', max_length=100)),
                ('pelindung', models.CharField(blank=True, max_length=100, null=True)),
                ('lain_lain', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Pengaman Pantai',
                'verbose_name_plural': 'Pengaman Pantai',
                'db_table': 'tb_pengaman_pantai',
            },
        ),
    ]
