# Generated by Django 5.0.14 on 2026-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengamanPantai', '0005_alter_pengamanpantaimodel_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengamanpantaimodel',
            name='jenis_bangunan',
            field=models.CharField(choices=[('Revetman', 'Revetman'), ('Break Water', 'Break Water'), ('Seawall', 'Seawall'), ('Pasangan Batu', 'Pasangan Batu'), ('Tanggul Laut', 'Tanggul Laut')], max_length=100),
        ),
    ]
