# Generated by Django 5.0.14 on 2026-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danau', '0002_danaumodel_created_by_danaumodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danaumodel',
            name='irigasi',
            field=models.FloatField(blank=True, null=True, verbose_name='Irigasi (Ha)'),
        ),
    ]
