# Generated by Django 5.0.14 on 2026-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danau', '0003_alter_danaumodel_irigasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danaumodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danaumodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
