# Generated by Django 5.0.14 on 2026-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danau', '0004_alter_danaumodel_latitude_alter_danaumodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danaumodel',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='danaumodel',
            unique_together={('nama',)},
        ),
    ]
