# Generated by Django 5.0.14 on 2026-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danau', '0005_alter_danaumodel_provinsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danaumodel',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('Papua Barat', 'Papua Barat'), ('Papua Barat Daya', 'Papua Barat Daya')], max_length=100, null=True),
        ),
    ]
